app/galletas/forms.py
from wtforms import Form, StringField, FloatField, IntegerField, validators

def no_caracteres_especiales(form, field):
    if not field.data:
        return
    if not field.data.isalnum() and ' ' not in field.data:
        raise validators.ValidationError("El campo no debe contener caracteres especiales")

class galletaForm(Form):
    id = IntegerField('id')
    nombre_galleta = StringField("Nombre de la galleta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.Length(min=1, max=80, message="Ingresa un nombre valido"),
        no_caracteres_especiales
    ])
    precio_unitario = FloatField("Precio unitario de la galleta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=.1)

        ])
    precio_kilo = FloatField("Precio por kilo", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=.1)
        ])
    descripcion = StringField("Descripcion de la receta", [
        validators.DataRequired(message="El campo es requerido"),
        no_caracteres_especiales
        ])
    peso_galleta = FloatField("Peso unitario de la galleta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=.1)

    ])

app/galletas/__init__.py
from flask import Blueprint

galletas = Blueprint('galletas',__name__)

from . import routes

app/galletas/routes.py
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required
from .forms import galletaForm
from . import galletas
from app.models.models import db, Galletas
from app.permissions import admin_permission

@galletas.route('/', methods=['GET', 'POST'])
@admin_permission.require(http_exception=403)
@login_required
def index():
    form = galletaForm()
    status = request.form.get('status', '1')
    galletas = Galletas.query.filter_by(status=status).all()
    return render_template("galletas/galletas.html", galletas=galletas, form=form, status=status)
@galletas.route('/save', methods=['POST'])
@login_required
def save():
    form = galletaForm(request.form)
    try:
        if form.validate():
            if form.id.data != 0:
                galleta = Galletas.query.get(form.id.data)
                if not galleta:
                    flash('Galleta not found', 'danger')
                    return redirect(url_for('galletas.index'))
                galleta.nombre_galleta = form.nombre_galleta.data
                galleta.precio_unitario = form.precio_unitario.data
                galleta.precio_kilo = form.precio_kilo.data
                galleta.descripcion = form.descripcion.data
                galleta.peso_galleta = form.peso_galleta.data
                flash('Galleta updated successfully', 'success')
            else:
                galleta = Galletas(nombre_galleta=form.nombre_galleta.data,
                                   precio_unitario=form.precio_unitario.data,
                                   precio_kilo=form.precio_kilo.data,
                                   descripcion=form.descripcion.data,
                                   peso_galleta=form.peso_galleta.data)
                db.session.add(galleta)
                flash('Galleta added successfully', 'success')
            db.session.commit()
            return redirect(url_for('galletas.index'))
        else:
            error_messages = "; ".join([f"{field}: {', '.join(errors)}" for field, errors in form.errors.items()])
            flash(f'Error al agregar galleta, introdusca solo caracteres validos', 'danger')
            return redirect(url_for('galletas.index'))
    except Exception as e:
        db.session.rollback()
        flash(f'Error al agregar galleta, introdusca solo caracteres validos', 'danger')  # Convertir el error a cadena de texto
        return redirect(url_for('galletas.index'))

@galletas.route('/delete', methods=['POST'])
@admin_permission.require(http_exception=403)
@login_required
def delete():
    id = request.form.get('id')
    galleta = Galletas.query.get(id)
    if galleta:
        galleta.status = 0
        db.session.commit()
        flash('Supplier deactivated successfully', 'success')
    else:
        flash('Galleta not found', 'danger')
    return redirect(url_for('galletas.index'))

@galletas.route('/activate', methods=['POST'])
@admin_permission.require(http_exception=403)
@login_required
def activate():
    id = request.form.get('id')
    galleta = Galletas.query.get(id)
    if galleta:
        galleta.status = 1
        db.session.commit()
        flash('Supplier activated successfully', 'success')
    else:
        flash('Galleta not found', 'danger')
    return redirect(url_for('galletas.index'))

app/templates/galletas/galletas.html
{% extends 'layout.html' %}
{% from "_macros.html" import render_field %}
{% block content %}
<div class="container-fluid p-3">

  <div class="row justify-content-center">
    <div class="col-12">
      <h1>Galletas</h1>
    </div>
    <hr>
    <div class="col-6">
      <button type="button" class="btn btn-primary" id="addCookie">
        Agregar galleta
      </button>
    </div>
    <div class="col-6">
      <form method="POST" action="{{ url_for('galletas.index') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-6 form-check">
              <input class="form-check-input" type="radio" name="status" id="active" value="1" {{ 'checked' if status == '1' else '' }}>
              <label class="form-check-label" for="active">
                Activos
              </label>
            </div>
            <div class="col-6 form-check">
              <input class="form-check-input" type="radio" name="status" id="inactive" value="0" {{ 'checked' if status == '0' else '' }}>
              <label class="form-check-label" for="inactive">
                Inactivos
              </label>
            </div>
            <div class="col-12 d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
          </div>
        </div>
      </form>
    </div>
    <div class="col-11">
      <table id="tblCookie" class="table table-striped responsive nowrap" style="width:100%">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Precio unitario</th>
            <th>Precio kilo</th>
            <th>Descripción</th>
            <th>Peso galleta</th>
            <th>Modificar</th>
            <th>Eliminar</th>
          </tr>
        </thead>
        <tbody>
          {% for g in galletas %}
          <tr data-id="{{ g.id }}">
            <td>{{ g.nombre_galleta }}</td>
            <td>{{ g.precio_unitario }}</td>
            <td>{{ g.precio_kilo }}</td>
            <td>{{ g.descripcion }}</td>
            <td>{{ g.peso_galleta }}</td>
            <td>
              <button class="btn btn-primary btn-sm" onclick="editCookie('{{ g.id }}')">Modificar</button>
            </td>
            <td>
              {% if g.status == 0 %}
              <form method="POST" action="{{ url_for('galletas.activate') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ g.id }}" id="id">
                <button type="submit" class="btn btn-success btn-sm confirm-submit">Activar</button>
              </form>
              {% else %}
              <form method="POST" action="{{ url_for('galletas.delete') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ g.id }}" id="id">
                <button type="submit" class="btn btn-danger btn-sm confirm-submit">Eliminar</button>
              </form>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <br>

  <form id="hiddenForm" method="POST" action="{{ url_for('galletas.save') }}" style="display: none;">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" id="hiddenId">
    {{ render_field(form.nombre_galleta, class="form-control", type="hidden") }}
    {{ render_field(form.precio_unitario, class="form-control", type="hidden") }}
    {{ render_field(form.precio_kilo, class="form-control", type="hidden") }}
    {{ render_field(form.descripcion, class="form-control", type="hidden") }}
    {{ render_field(form.peso_galleta, class="form-control", type="hidden") }}
  </form>
</div>

<script src="../static/js/galleta.js"></script>
{% endblock %}