app/recetas/forms.py
from wtforms import Form, StringField, FloatField, IntegerField, validators

def no_caracteres_especiales(form, field):
    if not field.data:
        return
    if not field.data.isalnum() and ' ' not in field.data:
        raise validators.ValidationError("El campo no debe contener caracteres especiales")

class recetaForm(Form):
    id = IntegerField('id')
    nombre_receta = StringField("Nombre de la rectea", [
        validators.DataRequired(message="El campo es requerido"),
        validators.Length(min=1, message="Ingresa un nombre valido"),
        no_caracteres_especiales
    ])
    descripcion = StringField("Descripcion de la receta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.Length(min=1, message="Ingresa un nombre valido"),
        no_caracteres_especiales
    ])
    galleta = IntegerField("ID de la Galleta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=1)
    ])
    cantidad_produccion = IntegerField("Cantidad de galletas por Reeceta", [
        validators.DataRequired(message="El campo es requerido"),
        validators.NumberRange(min=1)
    ])

app/recetas/__init__.py
from flask import Blueprint

recetas = Blueprint('recetas',__name__)

from . import routes

app/recetas/routes.py
from flask import render_template, request, flash, redirect, url_for,jsonify
from flask_login import login_required
from .forms import recetaForm
from . import recetas
from app.models.models import db, Recetas,Galletas,Supplies,Detalles_receta
from app.permissions import admin_permission
import json


@recetas.route('/', methods=['GET', 'POST'])
@admin_permission.require(http_exception=403)
@login_required
def index():
    form = recetaForm()
    status = request.form.get('status', '1')
    recetas = Recetas.query.filter_by(status=status).all()
    galletas = Galletas.query.filter_by(status=status).all()
    galletas_data = [{'id': galleta.id, 'nombre_galleta': galleta.nombre_galleta} for galleta in galletas]
    materia_prima = Supplies.query.all()
    materia_prima_data = [{'id': materia.id, 'nombre': materia.nombre, 'unidad_medida': materia.unidad_medida} for materia in materia_prima]   
    
    detalles_receta = Detalles_receta.query.join(Supplies, Detalles_receta.id_materia_prima == Supplies.id) \
        .add_columns(Supplies.nombre, Detalles_receta.cantidad, Detalles_receta.id_receta, Supplies.unidad_medida) \
        .all()
    
    detalles_json = [{
        'nombre': detalle[1],
        'cantidad': detalle[2],
        'unidad_medida': detalle[4],
        'id_receta': detalle[3]
    } for detalle in detalles_receta]
    
    print(detalles_json)

    return render_template("recetas/recetas.html", recetas=recetas, form=form, status=status, galletas=galletas_data, materias=materia_prima_data, detalles_json=detalles_json)


@recetas.route('/save_detalles', methods=['POST'])
@admin_permission.require(http_exception=403)
@login_required
def save_detalles():
    try:
        detalles_receta = json.loads(request.form.get('detalles_receta'))

        for detalle in detalles_receta:
            detalle_receta = Detalles_receta(
                id_receta=detalle['id_receta'],  # Corregido aquí
                id_materia_prima=detalle['id_materia_prima'],
                cantidad=detalle['cantidad']
            )
            db.session.add(detalle_receta)

        db.session.commit()
        flash('Detalles de la receta guardados correctamente', 'success')
        return redirect(url_for('recetas.index'))

    except Exception as e:
        db.session.rollback()
        flash('Error al guardar detalles de la receta', 'danger')
        return redirect(url_for('recetas.index'))



@recetas.route('/save', methods=['POST'])
@admin_permission.require(http_exception=403)
@login_required
def save():
    form = recetaForm(request.form)
    try:
        if form.validate():
            if form.id.data != 0:
                receta = Recetas.query.get(form.id.data)
                if not receta:
                    flash('Receta not found', 'danger')
                    return redirect(url_for('recetas.index'))
                receta.nombre_receta = form.nombre_receta.data
                receta.descripcion = form.descripcion.data
                receta.cantidad_produccion = form.cantidad_produccion.data
                receta.id_galleta = form.galleta.data  # Corregido aquí
                flash('Receta updated successfully', 'success')
            else:
                receta = Recetas(nombre_receta=form.nombre_receta.data,
                                 descripcion=form.descripcion.data,
                                 cantidad_produccion=form.cantidad_produccion.data,
                                 id_galleta=form.galleta.data)  # Corregido aquí
                db.session.add(receta)
                flash('Receta added successfully', 'success')
            db.session.commit()
            return redirect(url_for('recetas.index'))
        else:
            error_messages = "; ".join([f"{field}: {', '.join(errors)}" for field, errors in form.errors.items()])
            flash(f'Error al agregar receta: {error_messages}', 'danger')
            return redirect(url_for('recetas.index'))
    except Exception as e:
        db.session.rollback()
        flash('Error al agregar receta', 'danger')
        return redirect(url_for('recetas.index'))



@recetas.route('/delete', methods=['POST'])
@admin_permission.require(http_exception=403)
@login_required
def delete():
    id = request.form.get('id')
    receta = Recetas.query.get(id)
    if receta:
        receta.status = 0
        db.session.commit()
        flash('Receta deactivated successfully', 'success')
    else:
        flash('Receta not found', 'danger')
    return redirect(url_for('recetas.index'))

@recetas.route('/activate', methods=['POST'])
@login_required
def activate():
    id = request.form.get('id')
    receta = Recetas.query.get(id)
    if receta:
        receta.status = 1
        db.session.commit()
        flash('Receta activated successfully', 'success')
    else:
        flash('Receta not found', 'danger')
    return redirect(url_for('recetas.index'))

app/templates/recetas/recetas.html
{% extends 'layout.html' %}
{% from "_macros.html" import render_field %}
{% block content %}
<div class="container-fluid p-3">

  <div class="row justify-content-center">
    <div class="col-12">
      <h1>Recetas</h1>
    </div>
    <hr>
    <div class="col-6">
      <button type="button" class="btn btn-primary" id="addReceta" data-galletas="{{ galletas }}">Agregar receta</button>
    </div>
    <div class="col-6">
      <form method="POST" action="{{ url_for('recetas.index') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-6 form-check">
              <input class="form-check-input" type="radio" name="status" id="active" value="1" {{ 'checked' if status == '1' else '' }}>
              <label class="form-check-label" for="active">
                Activos
              </label>
            </div>
            <div class="col-6 form-check">
              <input class="form-check-input" type="radio" name="status" id="inactive" value="0" {{ 'checked' if status == '0' else '' }}>
              <label class="form-check-label" for="inactive">
                Inactivos
              </label>
            </div>
            <div class="col-12 d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
          </div>
        </div>
      </form>
    </div>
    <div class="col-11">
      <table id="tblReceta" class="table table-striped responsive nowrap" style="width:100%">
        <thead>
          <tr>
            <th>Nombre </th>
            <th>Descripcion </th>
            <th>Galleta</th>
            <th>Cantidad</th>
            <th>Modificar</th>
            <th>Eliminar</th>
            <th>Ingredientes</th>
            <th>Detalles</th>

          </tr>
        </thead>
        <tbody>
          {% for r in recetas %}
          <tr data-id="{{ r.id }}">
            <td>{{ r.nombre_receta}}</td>
            <td>{{ r.descripcion}}</td>
            <td value="{{ r.id_galleta }}">{{ r.galleta.nombre_galleta }}</td>
            <td>{{ r.cantidad_produccion }}</td>
            <td>
              <button class="btn btn-primary btn-sm" onclick="editReceta('{{ r.id }}')">Modificar</button>
            </td>
            <td>
              {% if r.status == 0 %}
              <form method="POST" action="{{ url_for('recetas.activate') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ r.id }}" id="activate_{{ r.id }}">
                <button type="submit" class="btn btn-success btn-sm confirm-submit">Activar</button>
              </form>
              {% else %}
              <form method="POST" action="{{ url_for('recetas.delete') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ r.id }}" id="delete_{{ r.id }}"> 
                <button type="submit" class="btn btn-danger btn-sm confirm-submit">Eliminar</button>
              </form>
              {% endif %}
            </td>
            <td>
              <button class="btn btn-primary btn-sm" data-id="{{ r.id }}"  onclick="addIngredientesEnBucle('{{ r.id }}')">Agregar Ingredientes</button>
            </td>
            <td>
              <button class="btn btn-primary btn-sm ver-detalles" data-id-receta="{{ r.id }}" >Ver detalles</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-12">
      <table id="tblDetallesReceta" class="table table-striped responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Materia Prima</th>
                <th>Cantidad</th>
                <th>ID Receta</th> <!-- Nueva columna -->
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <!-- Aquí se agregarán dinámicamente los detalles de la receta -->
        </tbody>
    </table>
    
    </div>
    <div class="col-12 d-flex justify-content-center">
      <button type="button" class="btn btn-primary" id="finalizar">Finalizar</button>
    </div>
 
  </div>

  <br>

  <form id="hiddenForm" method="POST" action="{{ url_for('recetas.save') }}" style="display: none;">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id" id="hiddenId">
    <input type="hidden" name="nombre_receta" id="nombre_receta">
    <input type="hidden" name="descripcion" id="descripcion">
    <input type="hidden" name="galleta" id="id_galleta">
    <input type="hidden" name="cantidad_produccion" id="cantidad_produccion">
  </form>
  <form id="formDetallesReceta" method="POST" action="{{ url_for('recetas.save_detalles') }}" style="display: none;">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="hidden" name="id_receta" id="id_receta">
    <input type="hidden" name="detalles_receta" id="detalles_receta">
</form>


<form id="formVerDetallesReceta" method="POST"  style="display: none;">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <input type="hidden" name="id_receta" id="id_receta_form">
</form>

</div>

<script>
  var galletas = {{ galletas | tojson }};
  var materias = {{ materias | tojson }};
  var detalles_json = {{ detalles_json | tojson }};
</script>

<script src="../static/js/recetas.js"></script>
{% endblock %}